server:
  port:          "8080"

db:
  host:          "rabbit-postgres"
  port:          "5432"
  username:      "postgres"
  password:      "postgres"
  name:          "group-manager"
  sslmode:       "disable"
  migration_dir: "migration"

rabbit:
  address: amqp://guest:guest@rabbit-rabbitmq:5672/
  exchanger: exchanger