server:
  port:          "8080"

db:
  host:          "localhost"
  port:          "5432"
  username:      "postgres"
  password:      "postgres"
  dbname:        "group-manager"
  sslmode:       "disable"
  migration_dir: "migration"

rabbit:
  address:
  exchanger: exchanger